---
# tasks file for nvm
# https://github.com/creationix/nvm#git-install
#
- name: Create directories
  file:
    dest: "{{ nvm_dir | dirname }}"
    state: directory
- name: Clone nvm
  git:
    repo: "{{ nvm_repo }}"
    dest: "{{ nvm_dir }}"
    version: "{{ nvm_version }}"
    update: "{{ nvm_update }}"
- block:
  - name: Add configurations to ~/.bashrc, ~/.profile, or ~/.zshrc or etc
    lineinfile:
      dest: "{{ nvm_rc_path }}"
      line: 'export NVM_DIR="{{ nvm_dir }}"'
      regexp: '^export NVM_DIR='
      create: yes
  - name: Add configurations to ~/.bashrc, ~/.profile, or ~/.zshrc or etc
    lineinfile:
      dest: "{{ nvm_rc_path }}"
      line: '[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"'
      create: yes
  when: nvm_rc_path != "NOT ADD"
